version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "TheApiT35t"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - taskapp-network
    volumes:
      - sql-data:/var/opt/mssql

  taskapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskapi
    ports:
      - "51000:51000"
    networks:
      - taskapp-network
    depends_on:
      - sqlserver

networks:
  taskapp-network:

volumes:
  sql-data: